version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis_rest_api_mikail
    ports:
      - "6379:6379"
    restart: always
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_services
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql